#!/bin/sh

sources='
src/config.js
src/rendering.js
src/stylesheet.js
src/ui.js
src/arrange.js
src/hash.js
src/logic.js
src/charts.js
src/core.js
src/hash_retrieval.js
src/index.js
'

echo '(function() {"use strict";' # You can remove "use strict" if you like

echo 'function vaccineDefines() {'
cat $sources
echo '}'

cat src/vaccine.js

echo '}());'
