#!/usr/bin/env node
var fs = require('fs'),
    exec = require('child_process').exec,
    assetStore = require('asset_store');

var replaceAsset = function(asset) {
  return function(text) {
    return text.replace('/' + asset.name, asset.url);
  };
};

var afterUpload = function() {
  var assets = assetStore.assets();
  var transforms = Object.keys(assets).map(function(name) {
    return replaceAsset(assets[name]);
  });
  exec('./configure.sh', function(err, text) {
    if (err) throw err;
    text = transforms.reduce(function(text, trans) {
      return trans(text);
    }, text);
    fs.writeFile('public/index.html', text, 'utf8', function(err) {
      if (err) throw err;
      console.log('-----> index.html written');
    });
  });
};

exec('./build.sh', {maxBuffer: 400000}, function(err, datazookaText) {
  if (err) throw err;
  var definitions = assetStore.findDefinitions();
  definitions.push({name: 'datazooka.js', text: datazookaText});
  assetStore.upload(definitions, afterUpload);
});
